[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r telegram_swiper_web/requirements.txt"]

[start]
cmd = "cd telegram_swiper_web/backend && python app.py"
