services:
  - type: web
    name: telegram-swiper
    env: python
    region: frankfurt
    buildCommand: pip install -r telegram_swiper_web/requirements.txt
    startCommand: cd telegram_swiper_web/backend && gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
